typography_spectrum: 0.4743439091835171
color:
  brandStrength: 0.2581233996897936
  lightness: 0.9921909736003727
  saturation: 0.21162493783049285
  rhythmicContrast: 0.8563197038602084
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
layout_spectrum: 0.011552451644092798
name: Gooey Prickles
navigation:
  - name: 2015 Reel
    id: b2387ff4-32cb-41c2-be27-1948d3c101e4
    type: content
  - name: 'Survive: Detroit'
    url: 'https://vimeo.com/69936371'
    type: external
  - name: Supervivere - Detroit
    url: 'http://www.superviveredesign.com/#/survive-detroit/'
    type: external
title: SHOW REEL
description: '2016'
